/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl.polsl.GUI;

import pl.polsl.model.Integration;
import pl.polsl.model.MidPoint;
import pl.polsl.model.NotAbstractClassException;
import pl.polsl.model.Trapezoidal;

/**
 *
 * @author Karol Pisarski
 * @version 1.0
 */
public class Window extends javax.swing.JFrame {

    private Integration integr = new Integration();
    
    private Integration calculatableIntegr;
    
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMethod = new javax.swing.ButtonGroup();
        jPanelMain = new javax.swing.JPanel();
        jToggleButtonCalculate = new javax.swing.JToggleButton();
        jRadioButtonTrap = new javax.swing.JRadioButton();
        jRadioButtonMidP = new javax.swing.JRadioButton();
        jLabelChose = new javax.swing.JLabel();
        jLabelRes = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        jTextFieldLB = new javax.swing.JTextField();
        jTextFieldUB = new javax.swing.JTextField();
        jTextFieldPrec = new javax.swing.JTextField();
        jLabelLowerBoundary = new javax.swing.JLabel();
        jLabelUpperBoundary = new javax.swing.JLabel();
        jLabelPrecision = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButtonCalculate.setText("Calculate");
        jToggleButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCalculateActionPerformed(evt);
            }
        });

        buttonGroupMethod.add(jRadioButtonTrap);
        jRadioButtonTrap.setText("Trapezoidal");
        jRadioButtonTrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTrapActionPerformed(evt);
            }
        });

        buttonGroupMethod.add(jRadioButtonMidP);
        jRadioButtonMidP.setText("Midpoint");
        jRadioButtonMidP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMidPActionPerformed(evt);
            }
        });

        jLabelChose.setText("Choose the calculating mehtod:");

        jLabelRes.setText("Result: ");

        jTextFieldLB.setText("2");
        jTextFieldLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLBActionPerformed(evt);
            }
        });

        jTextFieldUB.setText("4");
        jTextFieldUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUBActionPerformed(evt);
            }
        });

        jTextFieldPrec.setText("1000");
        jTextFieldPrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecActionPerformed(evt);
            }
        });

        jLabelLowerBoundary.setText("Lower Boundary");

        jLabelUpperBoundary.setText("Upper Boundary");

        jLabelPrecision.setText("Precision");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelChose))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jRadioButtonTrap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelRes))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jRadioButtonMidP)
                                .addGap(124, 124, 124)
                                .addComponent(jToggleButtonCalculate)
                                .addGap(0, 147, Short.MAX_VALUE)))))
                .addGap(36, 36, 36)
                .addComponent(jLabelResult)
                .addGap(94, 94, 94))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUpperBoundary)
                    .addComponent(jLabelPrecision)
                    .addComponent(jLabelLowerBoundary)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldUB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelLowerBoundary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabelUpperBoundary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabelPrecision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabelChose)
                .addGap(34, 34, 34)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTrap)
                    .addComponent(jLabelRes)
                    .addComponent(jLabelResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonCalculate)
                    .addComponent(jRadioButtonMidP))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMidPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMidPActionPerformed
        // TODO add your handling code here:
        
        calculatableIntegr = new MidPoint(integr);
        
    }//GEN-LAST:event_jRadioButtonMidPActionPerformed

    private void jToggleButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCalculateActionPerformed
        // TODO add your handling code here:
        //Trapezoidal integ = new Trapezoidal(integr);
        //integ.setLowerBound(2);
        //integ.setUpperBound(4);
        //integ.setPrecision(10000);
        if(jRadioButtonTrap.isSelected() || jRadioButtonMidP.isSelected())
        {
            try
            {
                jLabelResult.setText( String.valueOf(calculatableIntegr.calculateIntegral( x -> { return Math.pow(x,2); } ) ) );

            } 
            catch(NotAbstractClassException ex)
            {
                
            }    
        }
       //jLabelResult.setText(String.valueOf(integr.getLowerBound()) );
    }//GEN-LAST:event_jToggleButtonCalculateActionPerformed

    private void jRadioButtonTrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTrapActionPerformed
        // TODO add your handling code here:
        calculatableIntegr = new Trapezoidal(integr);
    }//GEN-LAST:event_jRadioButtonTrapActionPerformed

    private void jTextFieldUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUBActionPerformed
        // TODO add your handling code here:
        integr.setUpperBound(Double.parseDouble(jTextFieldUB.getText()) );

    }//GEN-LAST:event_jTextFieldUBActionPerformed

    private void jTextFieldLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLBActionPerformed
        // TODO add your handling code here:
        integr.setLowerBound(Double.parseDouble(jTextFieldLB.getText()) );
    }//GEN-LAST:event_jTextFieldLBActionPerformed

    private void jTextFieldPrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecActionPerformed
        // TODO add your handling code here:
        integr.setPrecision(Double.parseDouble(jTextFieldPrec.getText()) );
    }//GEN-LAST:event_jTextFieldPrecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMethod;
    private javax.swing.JLabel jLabelChose;
    private javax.swing.JLabel jLabelLowerBoundary;
    private javax.swing.JLabel jLabelPrecision;
    private javax.swing.JLabel jLabelRes;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelUpperBoundary;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JRadioButton jRadioButtonMidP;
    private javax.swing.JRadioButton jRadioButtonTrap;
    private javax.swing.JTextField jTextFieldLB;
    private javax.swing.JTextField jTextFieldPrec;
    private javax.swing.JTextField jTextFieldUB;
    private javax.swing.JToggleButton jToggleButtonCalculate;
    // End of variables declaration//GEN-END:variables
}
